### PR TITLE
81 sup ctrl interfaces

### LINKED ISSUE #81: Add direct control interfaces for valve and compressor speed
Some research contributions use direct valve or compressor control for MPC studies. Adding supervisory control blocks for these models would be a good standard feature.

### PR DESCRIPTION
**Pull request by FWuellhorst**
This PR closes #81.
I explicitly did not add "Modelica internal" supervisory control as we do not have a use-case for this yet and a simple `extends` of the control subsystem enables the addition of a then naming independent Modelica internal supervisory control.

### CODE REVIEW

**Comment by FWuellhorst** [comment]
@PatrickHenkel1 I want to keep the changes in the valve control models as the current main has some wrong annotations which are removed automatically by Dymola. Can you do the review?

**Review by FWuellhorst — COMMENTED** [review]
@MaxBerktoldRWTH : I used the standard supervisory control block to possibly allow for Modelica-internal supervisory control. Thus, the names slightly change, you have to override the defaults the same way the other signals are overridden.

**Review by FWuellhorst — COMMENTED** [review]
Changes look good and work, going to merge this now.

**Review by MaxBerktoldRWTH — COMMENTED** [review]
Looks good. Although to be honest I'm not 100% sure what all the changes do.

**Review by MaxBerktoldRWTH — APPROVED** [review]

**Pull request merged**
